# Generated by Django 5.1.4 on 2024-12-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0003_rename_functiontype_tipofuncion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cine',
            name='foto_sede',
            field=models.ImageField(blank=True, null=True, upload_to='cines/sedes/'),
        ),
    ]
