# Generated by Django 5.1.4 on 2024-12-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0004_cine_foto_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='tipos_funcion',
            field=models.ManyToManyField(to='cines.tipofuncion'),
        ),
        migrations.AlterField(
            model_name='tipofuncion',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
