# Generated by Django 5.1.4 on 2024-12-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cines',
            new_name='Cine',
        ),
    ]
