# Generated by Django 5.1.4 on 2024-12-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cines', '0002_rename_cines_cine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunctionType',
            new_name='TipoFuncion',
        ),
        migrations.RenameField(
            model_name='tipofuncion',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='cine',
            name='function_types',
        ),
        migrations.AddField(
            model_name='cine',
            name='tipos_funcion',
            field=models.ManyToManyField(help_text='Seleccione los tipos de funciones disponibles en este cine', to='cines.tipofuncion'),
        ),
    ]
