# Generated by Django 5.1.4 on 2024-12-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la película', max_length=200)),
                ('sinopsis', models.TextField(help_text='Sinopsis de la película')),
                ('idioma', models.CharField(help_text='Idioma principal de la película', max_length=50)),
                ('disponible', models.BooleanField(default=True, help_text='Indica si la película está disponible')),
                ('poster', models.ImageField(help_text='Póster de la película', upload_to='posters/')),
                ('fecha_lanzamiento', models.DateField(help_text='Fecha de lanzamiento de la película')),
            ],
        ),
    ]
