# Generated by Django 5.1.4 on 2024-12-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('fecha_lanzamiento', models.DateField()),
            ],
        ),
    ]
