# Generated by Django 5.1.4 on 2024-12-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_lanzamiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idioma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.ImageField(upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
