# Generated by Django 5.1.4 on 2024-12-17 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carrito_usuario'),
        ('dulceria', '0001_initial'),
        ('peliculas', '0002_alter_pelicula_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='peliculas',
            field=models.ManyToManyField(related_name='carritos', through='carrito.ItemPelicula', to='peliculas.pelicula'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos_dulceria',
            field=models.ManyToManyField(related_name='carritos', through='carrito.ItemDulceria', to='dulceria.dulceria'),
        ),
        migrations.AlterField(
            model_name='itemdulceria',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito'),
        ),
        migrations.AlterField(
            model_name='itempelicula',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito'),
        ),
    ]
