# Generated by Django 5.1.4 on 2024-12-17 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carrito_peliculas_carrito_productos_dulceria_and_more'),
        ('dulceria', '0001_initial'),
        ('peliculas', '0002_alter_pelicula_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos_dulceria',
        ),
        migrations.RemoveField(
            model_name='itempelicula',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itempelicula',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_dulceria',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad_pelicula',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='pelicula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peliculas.pelicula'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto_dulceria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dulceria.dulceria'),
        ),
        migrations.DeleteModel(
            name='ItemDulceria',
        ),
        migrations.DeleteModel(
            name='ItemPelicula',
        ),
    ]
